#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-index4.ceda.ac.uk - 2021/05/29 16:05:02
# Search URL: http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P-HR.hist-1950.r1i1p2f1.Omon.zos.gn.v20181212|esgf-data3.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P-HR.hist-1950.r1i1p2f1.Omon.zos.gn.v20181212|esgf-data3.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195001-195012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195001-195012.nc' 'SHA256' '27d60ec4d3005bd2400f103988a35ee291f5b08c6c33bc47061d677252e54c2c'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195101-195112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195101-195112.nc' 'SHA256' '5bbae264e080b003ada9c0046c30514454228d8742df2171fb825e9925c74b4a'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195201-195212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195201-195212.nc' 'SHA256' '0a69f6ee42bdeebedc40ee9ef84b507f95e354e6d8abaa84160bae82d392a48c'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195301-195312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195301-195312.nc' 'SHA256' '238ea63a2f3cc07652a144a470c60b242cacba2abf2a25ff4db614801a7363cf'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195401-195412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195401-195412.nc' 'SHA256' 'e8fcefa2a095b171260eeb7b693242b0034b601c4bb6613487f7d75bcf5bc7cd'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195501-195512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195501-195512.nc' 'SHA256' '4ac02767c0702ea1f411d68b9fc23082202ca1b8c78242b9062c002881c2d9b8'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195601-195612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195601-195612.nc' 'SHA256' 'fe3f1581c3b054ee5f6edc47c1172c64a4d8636f5406a374a78b130b4de95ff0'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195701-195712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195701-195712.nc' 'SHA256' '036d2894d8a07ecee7d87dc691f86eff661825929f11c7517181319a55088324'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195801-195812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195801-195812.nc' 'SHA256' 'cb18be359120ff29db7b76f7a4d9d8c3248120a1a2fa9bef871540be1eb4b94a'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195901-195912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_195901-195912.nc' 'SHA256' 'b9d294d22cf12245406d3805b534884c0635b131321c634d97d07ca1e7e9ac02'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196001-196012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196001-196012.nc' 'SHA256' 'f595ca7f75d7ba18c832993b777bfc80a616a9c46701ed669ad54bf9b046f413'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196101-196112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196101-196112.nc' 'SHA256' '68325fa688c01ea5cbd0b736d35df2f411dc59de79122a046765c88e48f33f7b'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196201-196212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196201-196212.nc' 'SHA256' '1cc383e027676e5ab8ed07c84261e2cf138448c5a2378d525ea64752a4eb4892'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196301-196312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196301-196312.nc' 'SHA256' '26f442a940fb711480f087e55934a6b734025f256357a12c802265c39602dc56'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196401-196412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196401-196412.nc' 'SHA256' '0462adf266691bf87b0d5762e89e4365d40782efb8c7f6c6b87fe5b28e9ece5c'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196501-196512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196501-196512.nc' 'SHA256' '33d8ceefc3070cbfdf10da4574be370e131e184260e4147273736ea60e51bdc5'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196601-196612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196601-196612.nc' 'SHA256' '08e735f351c5ba05fab370e91f79aee9624001876f9c56cbc0ee7e6f8414e762'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196701-196712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196701-196712.nc' 'SHA256' '1534b481a8194963a01986a7a414cb27635244557d389927a20741e3806797f7'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196801-196812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196801-196812.nc' 'SHA256' '2edb47f3f7a869f6a750e26594ddcc14385302b6d7bad6a88c0de0209972a000'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196901-196912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_196901-196912.nc' 'SHA256' '7fdfb98f0c3363279688b152818a8b4f77eba5991f30681b2367cbe9cbd2e40c'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197001-197012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197001-197012.nc' 'SHA256' '682c3b886a44cc86e71569e2c2139a244521d90ee98cfe493de05d4361c5f046'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197101-197112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197101-197112.nc' 'SHA256' '78ad9249dee03e0a18c508d426711579c569662658af7054c39eb45fdbadc656'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197201-197212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197201-197212.nc' 'SHA256' '1c4710c1e237327f0e2d86322f39ea4082848eb7e9306af1b870e8e8f690fcc8'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197301-197312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197301-197312.nc' 'SHA256' 'ddb33c41e59ef45ee76b05b0c34a131ddb1778a73e57b5ac4103daeec58495bf'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197401-197412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197401-197412.nc' 'SHA256' '51288c62a981165cb027328f5289f9e8c5ffbd075cae9be63d525999c5a9a320'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197501-197512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197501-197512.nc' 'SHA256' '1a89faf0c9c137ebf95c0c4ff841c083f940402c309b92adf280141ff3967468'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197601-197612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197601-197612.nc' 'SHA256' 'f94c28ef042e0e2335fd8853a784500dd28e01f57e3ccd3a46f068e5b9509009'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197701-197712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197701-197712.nc' 'SHA256' '88a31523e2a7162558b494341da9f207605b1446bca8a24254ae16c8203c641a'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197801-197812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197801-197812.nc' 'SHA256' '3983f6017910bd36dd27e4ebe491e6c2e8172642eaa48ad90231e998f2678db6'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197901-197912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_197901-197912.nc' 'SHA256' '514d343870783f2e888579928e108a2123406a5c42c6253f864711fcb32a8c40'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198001-198012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198001-198012.nc' 'SHA256' '6174353ce13922f0fb17a584e6e83670c35d9478b8bb91ae3f6f24eab61d8693'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198101-198112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198101-198112.nc' 'SHA256' '5493b3bac9fa3c3a019d95c27e7169165544150dc42b1c4a7212729613cee807'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198201-198212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198201-198212.nc' 'SHA256' '42f4edf87c9f2338bc8b536124b20d75eab0f62911b283500630632c19bcfe8e'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198301-198312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198301-198312.nc' 'SHA256' '8b2611bd415bb15f9090b869d3256e21b2b76981e7f5fd953fa089a5f4341901'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198401-198412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198401-198412.nc' 'SHA256' '5e1170ae624117e4d9cd3f9b0b4fea4933166aab51f323dd441e914b7646b656'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198501-198512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198501-198512.nc' 'SHA256' '585f6375365a6555564121a7dc9f8d3dcfd4b82509a8b09ccfd6f01c37d6a6b4'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198601-198612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198601-198612.nc' 'SHA256' '7e2118516c9f4b4e4857a827a4470603c646dc24897e9e2286715765e92e8ff4'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198701-198712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198701-198712.nc' 'SHA256' 'd6863b5b71b43e86a851bd713045aaa53718e4f20f039b363fea0fddbf35fffe'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198801-198812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198801-198812.nc' 'SHA256' '51af18844dde1e3741193eda7bece246b6a97fc818d7ff39294b849a8b93dc7a'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198901-198912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_198901-198912.nc' 'SHA256' 'd5180a39fa74a71d40bd93815e8539bda1a1069ccef5a6b62136dccab7d2d7ef'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199001-199012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199001-199012.nc' 'SHA256' '4889c7204b5fc02bbb8be50b117943ea7029161ffe39f13ffd5a184ed9eda3ba'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199101-199112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199101-199112.nc' 'SHA256' 'ffd871c8fc69c87dff3c4c95d377305bc43e26d761612fd855f3550110ebe33f'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199201-199212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199201-199212.nc' 'SHA256' 'fe367a59e2ba692d338c436a4af2dcd4f7ed23e220d6764ed15c57f0e9e71725'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199301-199312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199301-199312.nc' 'SHA256' '282a43b1ea59787ca23c1830ab64e4c0c8685a2ba2d2f6bd01949d86175d5d71'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199401-199412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199401-199412.nc' 'SHA256' 'f9eecf55dff8f8c85979fa10d2d4eedcef0f32e694c87ef92191e1ec2538b291'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199501-199512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199501-199512.nc' 'SHA256' '71da327f02910f7c2cf21c94ee11701e7c70955c1661f1f7e1025fab12fa1fb3'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199601-199612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199601-199612.nc' 'SHA256' 'f87e3636dc5f4c3122a06b7f02f992e31cc9fee7cc78684fff2396874c414f36'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199701-199712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199701-199712.nc' 'SHA256' '615afea661ab170b522b763b321956c82a65d2c5b573c9d1e0e4eec16a8552c6'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199801-199812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199801-199812.nc' 'SHA256' '02adf0e9fa7128b6fe51b65bf4d98356884d42791faa01d9aadf3d1d513c1237'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199901-199912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_199901-199912.nc' 'SHA256' 'c483be66bb833b78a0f59b02ad908a8e7477555d26e502fc4de89ad9160071d2'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200001-200012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200001-200012.nc' 'SHA256' '29199a87e8ff94e9dbec8fcfd7028fb3958a727963c5e4a5cbf3851724cbafe0'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200101-200112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200101-200112.nc' 'SHA256' 'c5ca90927fce981945af57af6e83fa4d513b9d917f3b21f8a6a8fc54428e1e04'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200201-200212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200201-200212.nc' 'SHA256' 'b6852df551847718b90a28876eac43fe75b8249c9b530f795fe04f64bc55b5f1'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200301-200312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200301-200312.nc' 'SHA256' '831c084e22d7183ef8fcb2e6c9d08e8f37f14e183b23624936bf359b35fffd0a'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200401-200412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200401-200412.nc' 'SHA256' '6376f94daf259b2b8aa5d23905becac2d39c530cf9d7bb67bce3117a9d3c6000'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200501-200512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200501-200512.nc' 'SHA256' '837ed2b4a02df51d6ac6f06a15fe92b77e41250f30b1017198938e1013dd6998'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200601-200612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200601-200612.nc' 'SHA256' '4e01001de541e89f425582f793a96a781cf4eb665e0c3545f25a5b1023f5cd46'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200701-200712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200701-200712.nc' 'SHA256' '6867d54c3ad37de213675431e49e9a03cbef387d7833a4553aacd723e34f962e'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200801-200812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200801-200812.nc' 'SHA256' '3d7a7e170f918034c37848b27790190f1e62bbc2afdd822858746d6393c89ea1'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200901-200912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_200901-200912.nc' 'SHA256' '532a035b22610cf324fab540e81223ee8b356a477f0b9b3a0e0f8aca681c2fb0'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201001-201012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201001-201012.nc' 'SHA256' '262660e88b436e0e091d9f3fd391310c0558c7ffe7fb53d21071695de22a66be'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201101-201112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201101-201112.nc' 'SHA256' '478a93159a91d6cb7d6470a57faefd951c33497b826d81469c3e88245d2dd88c'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201201-201212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201201-201212.nc' 'SHA256' '367b622dfacae8f7eeaf68887b3d40d7e5fd62fa0d3764d35a29c2c4a2cf8cf5'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201301-201312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201301-201312.nc' 'SHA256' 'd760514e264fce1cdf6b2936e151d65975701852c41deed150f4b6005a05bb2f'
'zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201401-201412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P-HR/hist-1950/r1i1p2f1/Omon/zos/gn/v20181212/zos_Omon_EC-Earth3P-HR_hist-1950_r1i1p2f1_gn_201401-201412.nc' 'SHA256' '4a32c9b0dba85800db80824a0379f911975b9c8e7edc0e65c878826590c7cc3b'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
