#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-index4.ceda.ac.uk - 2021/07/26 14:55:08
# Search URL: http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.CMCC.CMCC-CM2-HR4.control-1950.r1i1p1f1.Omon.zos.gn.v20180509|esgf-data3.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf-index4.ceda.ac.uk/esg-search/wget/?distrib=false&dataset_id=CMIP6.HighResMIP.CMCC.CMCC-CM2-HR4.control-1950.r1i1p1f1.Omon.zos.gn.v20180509|esgf-data3.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195001-195012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195001-195012.nc' 'SHA256' 'faf1d79b23ad09c91377438c4017353caad3bb1cd1dd43a9b74c723f380c921a'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195101-195112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195101-195112.nc' 'SHA256' '7da3a6ac1c7b77dde4feeb3a30c427bf8d7b3182144d97da93a17ebd3e8f7e5d'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195201-195212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195201-195212.nc' 'SHA256' '90ae75e2516d89c5451f607c7970db1c1820b699afd4e96336610bd7023c0da2'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195301-195312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195301-195312.nc' 'SHA256' 'e3153abe1d67c05e254b2ce81a2e87bcabdb61133485f4f2e55033046b7f8600'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195401-195412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195401-195412.nc' 'SHA256' '0f12a0cfaed4d07761baa3ad48b237827eb33776090f709d08a4ec2005cd4a6a'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195501-195512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195501-195512.nc' 'SHA256' '0f3709f3e927b3d33c308c6e313c7314ddc2f76294ae4758e55d4f8ba8334dd0'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195601-195612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195601-195612.nc' 'SHA256' 'c0a76586b769fdf8c0890b1fe2eb91bf5b9f404d31e2d45e048675d8d3c5599f'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195701-195712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195701-195712.nc' 'SHA256' '9daeec882ee3d35353679f00838b8c47099c623e0091d999e14cba3af7a31db8'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195801-195812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195801-195812.nc' 'SHA256' '9074071b760b739e4713e10d8ccaba9430e63e8c10db78609daca7084897af75'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195901-195912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_195901-195912.nc' 'SHA256' 'e308237871c5604c716104f35ef7ceb669a33c6a94ec184a850df2887bf8f7c9'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196001-196012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196001-196012.nc' 'SHA256' '02f2c96223b3608cb2c95b7ae19d090700b6d411ce413f1c6ab3a9a1baa6a03d'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196101-196112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196101-196112.nc' 'SHA256' '5e9e50f79e2c6fc51f424aa672f11fab623f339168f5778e075c2e482e1c82bc'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196201-196212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196201-196212.nc' 'SHA256' '9953778d5569e897d0252d9e26a116f02dd5e6730220b94244ab5d0c6784880a'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196301-196312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196301-196312.nc' 'SHA256' '5e73c4aacfc8efff738604e5fb2bb386d644a28058a8c944d05cb38fdbc12743'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196401-196412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196401-196412.nc' 'SHA256' 'ea022afb68e067e088a63296b3dccac914ac0f1c05c6f11f156d136915f80132'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196501-196512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196501-196512.nc' 'SHA256' 'f30d74d814f9bef09fdd55de11bb744c1a251714616d1ef7597f89b10abeef6d'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196601-196612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196601-196612.nc' 'SHA256' '9b891cb2d5fcb63b94c3b6943192b584e32f72b1903f72ad926f045167487080'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196701-196712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196701-196712.nc' 'SHA256' 'ad7f3c445da30650e257efc9ac00f0d0426465813083bfc18b8353542a003af6'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196801-196812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196801-196812.nc' 'SHA256' '384a70354759b5d703b6a57441976f3bc7c0bff035291f6e4f16fb380178909f'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196901-196912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_196901-196912.nc' 'SHA256' 'aaf977841359ef7d415b32ee4c2105fbfff955685bfc8054bb1c776ff5637bce'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197001-197012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197001-197012.nc' 'SHA256' '3deb2c3806543f5c54d6b185b6402d24ef41ca7952b3028eef2abd04bb04435c'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197101-197112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197101-197112.nc' 'SHA256' 'b20f8525b87a3e920c35e6c3b4b4c32459c0856515526260e5e37635654fb152'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197201-197212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197201-197212.nc' 'SHA256' '633fb203c6fd85e47a22b739dddfc290892cc9f911991911785231da9f7f6ef1'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197301-197312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197301-197312.nc' 'SHA256' '0b5693408b4cbe91edeb7fdb50060545c33f150a77421e5d0d404b5c12f61a12'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197401-197412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197401-197412.nc' 'SHA256' 'e00ffeb7f02d75336ae8c4cc5f49b627512081cd9022e1563bbacfb16e3bdefd'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197501-197512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197501-197512.nc' 'SHA256' 'f437e3c1465db41cec65f949218f2f52f5a7fcc28c5857cde8b588bbeaf416e7'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197601-197612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197601-197612.nc' 'SHA256' '7c4291e3b8d388a673c259e5a3c00d8864a7dc3cbcfec732c67335c2ea8d0d00'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197701-197712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197701-197712.nc' 'SHA256' '0f1ed0ca76bfb2aa7604d36e9500fcbcefc30c19b48f6d054e8876746cf6aff1'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197801-197812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197801-197812.nc' 'SHA256' 'e11520a9dd8df06d7b2412d3c36580cf6547b7da953ad2cef513c0c0937b5442'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197901-197912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_197901-197912.nc' 'SHA256' '07c1eda937a6a969b8702f3230a608bad714cf7ba7b02e33ec002decf9d25266'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198001-198012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198001-198012.nc' 'SHA256' '28ce9a500d3dcbb1b3029711ded64f543c8389760858d0a21ce609417b089b0d'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198101-198112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198101-198112.nc' 'SHA256' '07d9b58f8351c1d95b1adc15c4446652e9f4724c2cdd78d4b8ecf523c7f432c0'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198201-198212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198201-198212.nc' 'SHA256' 'de7135122557e9142a8c9df8255a621ba860196fdbfe36df8568d119d045b992'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198301-198312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198301-198312.nc' 'SHA256' '7b326257d58d9354b3f7e0628f31d8ce05156b09e6efe16382ce22a25701c3b9'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198401-198412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198401-198412.nc' 'SHA256' '75ca17a9d5db70740e2c4bb468d5d8dade0c326329de8bc6583dedb795a9f73f'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198501-198512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198501-198512.nc' 'SHA256' '67e907feb5bf8b36c48b4ff4a2d605d37bd0783784dc1a02e390903916a9e17d'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198601-198612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198601-198612.nc' 'SHA256' '3e383610f78febe84c2046f09a63167e9d9f30ab30ce876c4185826414b0f872'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198701-198712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198701-198712.nc' 'SHA256' '9ee8417319d851e4939e3c7a09747192097a7c1303c0777f84de60f3770337ae'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198801-198812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198801-198812.nc' 'SHA256' '72cb8c768718a515adfd9a0abad1b7cc2dc3ee39242cb40a536a2a82e9dbb469'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198901-198912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_198901-198912.nc' 'SHA256' '3accfed30d057b5dbc79455f4de4394b6cfdd4567818d323f20265d436d93d92'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199001-199012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199001-199012.nc' 'SHA256' 'f2342ff4b13f32ac53864b4066daddc8d5aaf55f9f8515369bcbd19bb7c3a9fa'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199101-199112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199101-199112.nc' 'SHA256' '3a33dcc52fee4772ed5daa8470fb6429dde4d5100434db437065b337d7fdf01b'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199201-199212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199201-199212.nc' 'SHA256' '80ce9e77c049b8ba253aeff87a7ba554e8d968a9abbbdf30e71f3267329b5eb4'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199301-199312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199301-199312.nc' 'SHA256' 'a06149f54410274944f665ee56fc55c4959faa9fa40a6153162cc45eb065c481'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199401-199412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199401-199412.nc' 'SHA256' '9aa2795e7bb75e68b2c5abe8adfeeb527652eb76effef01a6e970040f364655f'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199501-199512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199501-199512.nc' 'SHA256' '3bac0597ce1fdfa3037247eb0203fc1ee8db08b6b1422c9787b035d17c679a3a'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199601-199612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199601-199612.nc' 'SHA256' 'ea2bb5da297e947d894dcaedee3e2806d9d9730bb27c4c6a3080346c13f1c339'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199701-199712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199701-199712.nc' 'SHA256' '86c6510df80b4dcb78604bddf3613933f0237cacf30b6c1d3c99271afe7eb6d6'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199801-199812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199801-199812.nc' 'SHA256' '93df2736ba1bef9c758ebe968be0bcdf6eb1315550b1cce4f2145b22fe8dbb3b'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199901-199912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_199901-199912.nc' 'SHA256' 'eae695669553bdec84a5e5770ddf21bc1a2cc64e6b4bd8af97354f24437ac16c'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200001-200012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200001-200012.nc' 'SHA256' '2868a5366acfa7eda61c7bfd73cbf1f112536e1deb96b44840a4a4fbbeccab6e'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200101-200112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200101-200112.nc' 'SHA256' '98d90c2b88859030db2423ffc3b23899584f313b9611942deb00f1bac7335735'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200201-200212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200201-200212.nc' 'SHA256' '79c4e56a44b6091b2daf0fbd68bb66b585012f980c4691f92e97aa31cfb892a7'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200301-200312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200301-200312.nc' 'SHA256' 'ef2f7511567778fc3c1531afc7a22982701925b51ac53845e759f5870dd3e8af'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200401-200412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200401-200412.nc' 'SHA256' '7732ca958e5720dea5b654d1b270fdc8bf6ae75c2e90cbf3c0f8654492ee6ce0'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200501-200512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200501-200512.nc' 'SHA256' '149470fe4073ca0e480aa73f90fa1e8ddabe77eed82a34274851143eb160e81d'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200601-200612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200601-200612.nc' 'SHA256' 'df102e4d95e2ed7ca9ed4f0b6043b0486209aa8aeef4c5a3288772cf100186a9'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200701-200712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200701-200712.nc' 'SHA256' '6a0d2dfd1545fb2c48734309e2c4bb7b7d4704ba048e3e40afd23c735ed543e1'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200801-200812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200801-200812.nc' 'SHA256' '4faf6dace58dc92caebc03c0adbb99b6159e07a74a806296ea2854762fb385d6'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200901-200912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_200901-200912.nc' 'SHA256' '0ca7045abd73e36273df434e9cb28193ec608e682ca79d5a7317793cae9dd2b2'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201001-201012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201001-201012.nc' 'SHA256' '8387f29cb8f01dbc35e68d575183c84ce3eb63cdfe85b5183c3dbdcd29755355'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201101-201112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201101-201112.nc' 'SHA256' '16db6f01de8bbca08221cff353ba9df3379bc82bdb56df19822306d95f53653f'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201201-201212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201201-201212.nc' 'SHA256' '9ddc140881a5d3388e774b9df8158b787b04a77f7e54e37256e8434e44a4c173'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201301-201312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201301-201312.nc' 'SHA256' '58d8ec8044d1fb117348064658d090b4d111c7041b01c210647081fe6d8a8f53'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201401-201412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201401-201412.nc' 'SHA256' '3eac769608b69ed0fdf2bd3f79ee9358117d4020ba7a49601e01cea1e30f5e2b'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201501-201512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201501-201512.nc' 'SHA256' 'd7bfe9a3c1ff89fc22cf945f6cdb72d651fd7e6aaf8c2b0419e4aade07b9aa21'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201601-201612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201601-201612.nc' 'SHA256' 'c8c57017f2c5d7719101260dabb0e2381a2e93d6238893258f170e5bea09836f'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201701-201712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201701-201712.nc' 'SHA256' '0a5640624f13f94919713556ca330c3e91e02c8e2ef40ca7622edca81d31b6d1'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201801-201812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201801-201812.nc' 'SHA256' 'c74848249469fa3562f0854ead8ead8f99f7ecf865dac43c942f1787e5248982'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201901-201912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_201901-201912.nc' 'SHA256' '57e406e5937493cd61d2400cd1e64ed5094c6d01f98365a5c12aec80abca6242'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202001-202012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202001-202012.nc' 'SHA256' 'f81b5647b2326f8222110d8542e3c5df58efaf401b149c9e21fe7640d8159c17'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202101-202112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202101-202112.nc' 'SHA256' '2d44a40020bbef7c4c56bd492e6e3377f9c23418dc12fdf9e7d2f5168e41f801'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202201-202212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202201-202212.nc' 'SHA256' '0e4b583c91566db2ad88313ece67294cef0844c4c8d1cfece4f14adb8ebef144'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202301-202312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202301-202312.nc' 'SHA256' 'e6b440c1ffae90b81bdf19bf7e5da69eb8bd939af2094bc1a998e6b4a0c29442'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202401-202412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202401-202412.nc' 'SHA256' '678dd4acdcfd9120ff478adb79b20abf77e7786c6a7f5d3083ed757deb73008b'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202501-202512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202501-202512.nc' 'SHA256' '5c96c109fc48d650ff4de2f159a49b15a66be503dbf1eb9d66a4e70a43efe671'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202601-202612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202601-202612.nc' 'SHA256' '656ac9b6b3a9c6780ba4721b42dc8aad695b258d3aa3328be22195184f093046'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202701-202712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202701-202712.nc' 'SHA256' 'df3606a6745e92a8be13362950274130f514085cdc2baddd565887b6ac15c3fd'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202801-202812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202801-202812.nc' 'SHA256' '2dc96281e5d48702e7075cda11985a7ba8c049e5d4b8bdb5c115f82c25c2385b'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202901-202912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_202901-202912.nc' 'SHA256' '064fc6685d58d2d72f0bd7b979b2491b95be7b768e551460bd5711ba0907b818'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203001-203012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203001-203012.nc' 'SHA256' '968db8357f364c07f51ce84bc3587f56957536589d9c15c19b19e97bc1778de1'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203101-203112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203101-203112.nc' 'SHA256' '6c964f7d8638dbd063358558a9f7d944050019489c40cb8554179cfe2d75d6e5'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203201-203212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203201-203212.nc' 'SHA256' 'e870ce1ad96b510ca8f9df240ab889db80bc6bc028668328c1418b5014c3df8d'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203301-203312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203301-203312.nc' 'SHA256' '5fe627c0eb6963e234d53f3599515288348cd76146f4cf30374fdb022083a46e'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203401-203412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203401-203412.nc' 'SHA256' '07807f91e8b75285b3f32278f70e86230a8fc5231bd5605c975858f8c3f5f48f'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203501-203512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203501-203512.nc' 'SHA256' '5999181e907e61caa732ad82126eea17c5c5e7f9b7ae439a1e9f4460eb8e48c1'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203601-203612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203601-203612.nc' 'SHA256' '0d0ddb83832ce4797d3700045f88ee91214c509d46b1eddb3f16b653fb73e1ae'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203701-203712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203701-203712.nc' 'SHA256' '3c19c725a04be9934c4da10843afb4c67d6e1461930afa337a455d5b0d9a11f5'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203801-203812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203801-203812.nc' 'SHA256' 'e09c2505b90a38ea2150fb5560af8442ecb889218fceb01d2e5350da33ab8788'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203901-203912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_203901-203912.nc' 'SHA256' '001de3d2c7e67dc5cf30d9e25b98e7176d8eaed7528164cb5a9e9100c5ed57ce'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204001-204012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204001-204012.nc' 'SHA256' '84640fe61c2ca7a1ee8cace60fcc7fbd8b7a09f9570961e37ddc3150456c4da3'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204101-204112.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204101-204112.nc' 'SHA256' '8d0142d0558fca7b4405513d5b86b270dcbab8c3dc5ebd4298d50d64dca857e9'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204201-204212.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204201-204212.nc' 'SHA256' '48cc1b1fb8b0bb64079d047dd52a2c4e9f1724aa179b2da57dc2a1b4e36d3090'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204301-204312.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204301-204312.nc' 'SHA256' 'b2f04c437e5f841515b1f23fc5e4b941ce7c1cf25c91688fa2dfe20195ed09b8'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204401-204412.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204401-204412.nc' 'SHA256' '70c2ceb8fca47873eb649e80038f324e618ef66bb49774b7b362f0a208fa0cd0'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204501-204512.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204501-204512.nc' 'SHA256' '430a0b0ad97a365d24f7e8abf9da9d6c1a7d4e077ffea1ceef2b5f3f140b2921'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204601-204612.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204601-204612.nc' 'SHA256' '2205caa9548b2e313917c1f517a8ab678eea129cfd7a6e07a3878581608c6792'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204701-204712.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204701-204712.nc' 'SHA256' '2303e10a7546e782b51afcf72b7ac900ff089459ecdc0bbfbd0699b7341cc2a3'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204801-204812.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204801-204812.nc' 'SHA256' 'f179f94a75b8f5c25c6a4cf45bb43ed61ed5623cbb558719e8c246d44d3d4f56'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204901-204912.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_204901-204912.nc' 'SHA256' '2c6b6385848dbd15a1fc7e457aa6c97b40ddfaf8990197aa98f08e0415391c77'
'zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_205001-205012.nc' 'http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/control-1950/r1i1p1f1/Omon/zos/gn/v20180509/zos_Omon_CMCC-CM2-HR4_control-1950_r1i1p1f1_gn_205001-205012.nc' 'SHA256' 'f3fc5550ab8e0ddcd7a3401d6f7d1cc832ce40ea5d6e9cc5a20137ea79340ab5'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 101 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
